/*
 * generated by Xtext 2.25.0
 */
package org.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RegistrationDSLStandaloneSetup extends RegistrationDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new RegistrationDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
