/**
 * generated by Xtext 2.25.0
 */
package org.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.RegistrationDSLRuntimeModule;
import org.xtext.RegistrationDSLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RegistrationDSLIdeSetup extends RegistrationDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    RegistrationDSLRuntimeModule _registrationDSLRuntimeModule = new RegistrationDSLRuntimeModule();
    RegistrationDSLIdeModule _registrationDSLIdeModule = new RegistrationDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_registrationDSLRuntimeModule, _registrationDSLIdeModule));
  }
}
