/**
 * generated by Xtext 2.25.0
 */
package org.xtext.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RegistrationDSLIdeModule extends AbstractRegistrationDSLIdeModule {
}
