/*
 * generated by Xtext 2.25.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.registrationDSL.ui.internal.RegistrationDSLActivator;

public class RegistrationDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RegistrationDSLActivator.getInstance().getInjector("org.xtext.RegistrationDSL");
	}

}
