/*
 * generated by Xtext 2.25.0
 */
package org.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.RegistrationDSLRuntimeModule;
import org.xtext.RegistrationDSLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RegistrationDSLIdeSetup extends RegistrationDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RegistrationDSLRuntimeModule(), new RegistrationDSLIdeModule()));
	}
	
}
