/**
 * generated by Xtext 2.25.0
 */
package org.xtext.registrationDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.registrationDSL.Entity#getBase <em>Base</em>}</li>
 *   <li>{@link org.xtext.registrationDSL.Entity#getFields <em>Fields</em>}</li>
 * </ul>
 *
 * @see org.xtext.registrationDSL.RegistrationDSLPackage#getEntity()
 * @model
 * @generated
 */
public interface Entity extends Declaration
{
  /**
   * Returns the value of the '<em><b>Base</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base</em>' reference.
   * @see #setBase(Entity)
   * @see org.xtext.registrationDSL.RegistrationDSLPackage#getEntity_Base()
   * @model
   * @generated
   */
  Entity getBase();

  /**
   * Sets the value of the '{@link org.xtext.registrationDSL.Entity#getBase <em>Base</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Base</em>' reference.
   * @see #getBase()
   * @generated
   */
  void setBase(Entity value);

  /**
   * Returns the value of the '<em><b>Fields</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.registrationDSL.Field}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fields</em>' containment reference list.
   * @see org.xtext.registrationDSL.RegistrationDSLPackage#getEntity_Fields()
   * @model containment="true"
   * @generated
   */
  EList<Field> getFields();

} // Entity
