/**
 * generated by Xtext 2.25.0
 */
package org.xtext.registrationDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>External Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.registrationDSL.ExternalCall#getTarget <em>Target</em>}</li>
 *   <li>{@link org.xtext.registrationDSL.ExternalCall#getArguments <em>Arguments</em>}</li>
 * </ul>
 *
 * @see org.xtext.registrationDSL.RegistrationDSLPackage#getExternalCall()
 * @model
 * @generated
 */
public interface ExternalCall extends LogicExp
{
  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(External)
   * @see org.xtext.registrationDSL.RegistrationDSLPackage#getExternalCall_Target()
   * @model
   * @generated
   */
  External getTarget();

  /**
   * Sets the value of the '{@link org.xtext.registrationDSL.ExternalCall#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(External value);

  /**
   * Returns the value of the '<em><b>Arguments</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.registrationDSL.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arguments</em>' containment reference list.
   * @see org.xtext.registrationDSL.RegistrationDSLPackage#getExternalCall_Arguments()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getArguments();

} // ExternalCall
