/**
 * generated by Xtext 2.25.0
 */
package org.xtext.registrationDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Workflow</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.registrationDSL.RegistrationDSLPackage#getWorkflow()
 * @model
 * @generated
 */
public interface Workflow extends Declaration
{
} // Workflow
